
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.HBox hbox2;

	private global::Gtk.VSeparator vseparator10;

	private global::Gtk.Label label1;

	private global::Gtk.VSeparator vseparator2;

	private global::Gtk.Label label2;

	private global::Gtk.VBox vbox3;

	private global::Gtk.HBox hbox3;

	private global::Gtk.VSeparator vseparator8;

	private global::Gtk.SpinButton num1_spinbutton;

	private global::Gtk.VSeparator vseparator1;

	private global::Gtk.SpinButton num2_spinbutton;

	private global::Gtk.VSeparator vseparator9;

	private global::Gtk.HBox hbox4;

	private global::Gtk.VSeparator vseparator7;

	private global::Gtk.HScale num1_hscale1;

	private global::Gtk.Label label;

	private global::Gtk.HScale num2_hscale;

	private global::Gtk.VSeparator vseparator3;

	private global::Gtk.HBox hbox5;

	private global::Gtk.VSeparator vseparator5;

	private global::Gtk.Label result_lbl;

	private global::Gtk.VSeparator vseparator6;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Addition Sim 2019");
		this.Icon = global::Stetic.IconLoader.LoadIcon(this, "gtk-add", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(2));
		this.Resizable = false;
		this.AllowGrow = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vseparator10 = new global::Gtk.VSeparator();
		this.vseparator10.WidthRequest = 5;
		this.vseparator10.Name = "vseparator10";
		this.hbox2.Add(this.vseparator10);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vseparator10]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("First Number");
		this.hbox2.Add(this.label1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label1]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vseparator2 = new global::Gtk.VSeparator();
		this.vseparator2.WidthRequest = 116;
		this.vseparator2.Name = "vseparator2";
		this.hbox2.Add(this.vseparator2);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vseparator2]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Second Number");
		this.hbox2.Add(this.label2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label2]));
		w5.Position = 3;
		w5.Expand = false;
		w5.Fill = false;
		this.hbox1.Add(this.hbox2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hbox2]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vseparator8 = new global::Gtk.VSeparator();
		this.vseparator8.WidthRequest = 5;
		this.vseparator8.Name = "vseparator8";
		this.hbox3.Add(this.vseparator8);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vseparator8]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.num1_spinbutton = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.num1_spinbutton.CanFocus = true;
		this.num1_spinbutton.Name = "num1_spinbutton";
		this.num1_spinbutton.Adjustment.PageIncrement = 10D;
		this.num1_spinbutton.ClimbRate = 1D;
		this.num1_spinbutton.Numeric = true;
		this.hbox3.Add(this.num1_spinbutton);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.num1_spinbutton]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vseparator1 = new global::Gtk.VSeparator();
		this.vseparator1.WidthRequest = 185;
		this.vseparator1.CanDefault = true;
		this.vseparator1.Name = "vseparator1";
		this.hbox3.Add(this.vseparator1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vseparator1]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.num2_spinbutton = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.num2_spinbutton.CanFocus = true;
		this.num2_spinbutton.Name = "num2_spinbutton";
		this.num2_spinbutton.Adjustment.PageIncrement = 10D;
		this.num2_spinbutton.ClimbRate = 1D;
		this.num2_spinbutton.Numeric = true;
		this.hbox3.Add(this.num2_spinbutton);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.num2_spinbutton]));
		w11.Position = 3;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vseparator9 = new global::Gtk.VSeparator();
		this.vseparator9.WidthRequest = 5;
		this.vseparator9.Name = "vseparator9";
		this.hbox3.Add(this.vseparator9);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vseparator9]));
		w12.Position = 4;
		w12.Expand = false;
		w12.Fill = false;
		this.vbox3.Add(this.hbox3);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox3]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vseparator7 = new global::Gtk.VSeparator();
		this.vseparator7.WidthRequest = 5;
		this.vseparator7.Name = "vseparator7";
		this.hbox4.Add(this.vseparator7);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vseparator7]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.num1_hscale1 = new global::Gtk.HScale(null);
		this.num1_hscale1.CanFocus = true;
		this.num1_hscale1.Name = "num1_hscale1";
		this.num1_hscale1.Adjustment.Upper = 100D;
		this.num1_hscale1.Adjustment.PageIncrement = 10D;
		this.num1_hscale1.Adjustment.StepIncrement = 1D;
		this.num1_hscale1.DrawValue = true;
		this.num1_hscale1.Digits = 0;
		this.num1_hscale1.ValuePos = ((global::Gtk.PositionType)(2));
		this.hbox4.Add(this.num1_hscale1);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.num1_hscale1]));
		w15.Position = 1;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label = new global::Gtk.Label();
		this.label.WidthRequest = 70;
		this.label.Name = "label";
		this.label.LabelProp = global::Mono.Unix.Catalog.GetString("Result");
		this.label.UseUnderline = true;
		this.hbox4.Add(this.label);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label]));
		w16.Position = 2;
		w16.Expand = false;
		w16.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.num2_hscale = new global::Gtk.HScale(null);
		this.num2_hscale.CanFocus = true;
		this.num2_hscale.Name = "num2_hscale";
		this.num2_hscale.Adjustment.Upper = 100D;
		this.num2_hscale.Adjustment.PageIncrement = 10D;
		this.num2_hscale.Adjustment.StepIncrement = 1D;
		this.num2_hscale.DrawValue = true;
		this.num2_hscale.Digits = 0;
		this.num2_hscale.ValuePos = ((global::Gtk.PositionType)(2));
		this.hbox4.Add(this.num2_hscale);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.num2_hscale]));
		w17.Position = 3;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vseparator3 = new global::Gtk.VSeparator();
		this.vseparator3.WidthRequest = 5;
		this.vseparator3.Name = "vseparator3";
		this.hbox4.Add(this.vseparator3);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vseparator3]));
		w18.Position = 4;
		w18.Expand = false;
		w18.Fill = false;
		this.vbox3.Add(this.hbox4);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox4]));
		w19.Position = 1;
		w19.Expand = false;
		w19.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.vseparator5 = new global::Gtk.VSeparator();
		this.vseparator5.WidthRequest = 129;
		this.vseparator5.Name = "vseparator5";
		this.hbox5.Add(this.vseparator5);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.vseparator5]));
		w20.Position = 0;
		w20.Expand = false;
		w20.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.result_lbl = new global::Gtk.Label();
		this.result_lbl.WidthRequest = 69;
		this.result_lbl.Name = "result_lbl";
		this.result_lbl.LabelProp = global::Mono.Unix.Catalog.GetString("0");
		this.hbox5.Add(this.result_lbl);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.result_lbl]));
		w21.Position = 1;
		w21.Expand = false;
		w21.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.vseparator6 = new global::Gtk.VSeparator();
		this.vseparator6.WidthRequest = 110;
		this.vseparator6.Name = "vseparator6";
		this.hbox5.Add(this.vseparator6);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.vseparator6]));
		w22.Position = 2;
		w22.Expand = false;
		w22.Fill = false;
		this.vbox3.Add(this.hbox5);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox5]));
		w23.Position = 2;
		w23.Expand = false;
		w23.Fill = false;
		this.vbox1.Add(this.vbox3);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox3]));
		w24.Position = 1;
		w24.Expand = false;
		w24.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 336;
		this.DefaultHeight = 132;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.num1_spinbutton.ValueChanged += new global::System.EventHandler(this.num1_spinnerChanged);
		this.num2_spinbutton.ValueChanged += new global::System.EventHandler(this.num2_spinnerChanged);
		this.num1_hscale1.ValueChanged += new global::System.EventHandler(this.num1sliderChange);
		this.num2_hscale.ValueChanged += new global::System.EventHandler(this.num2sliderChange);
	}
}
